import React, { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { languages } from "@/app/i18n/settings";
import { dir } from "i18next";
import { ToastContainer } from "react-toastify";
import Sidebar from "@/app/[locale]/components/Global/Sidebar/Sidebar";
import dynamic from "next/dynamic";

const Navbar = dynamic(() => import("@/app/[locale]/components/Global/NavBar/Navbar"))

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



interface RootLayoutProps {
  params: {
    locale: string;
  };
  children: ReactNode;
}


export default async function RootLayout({ params: { locale }, children }: RootLayoutProps) {
  return (
    <html lang={locale} dir={dir(locale)} style={{direction : locale == "ar" ? "rtl" : "ltr"}}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="absolute ">
          {/* <BurgerMenu /> */}
        </div>
        <div className="fixed lg:relative z-40 bg-white w-full">
          <Navbar locale={locale} />
        </div>
        <div className="grid lg:grid-cols-[25%_72%] pt-16 lg:pt-0 gap-3 lg-pt-0 ">
          <div className="hidden lg:block">
            <Sidebar locale={locale} />
          </div>
          <div className={``}>
            {children}
          </div>
        </div>
        <div className="">
          {/* <Footer /> */}
        </div>

        <ToastContainer />
      </body>
    </html>
  );
}
