import React, { ReactNode } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
// import { languages } from "@/app/i18n/settings";
import { dir } from "i18next";
import dynamic from "next/dynamic";
import { MyProvider } from './context/myContext';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { GetInfo, GetLogoAndIcon } from "./api/info";
const Navbar = dynamic(() => import("@/app/[locale]/components/Global/NavBar/Navbar"), { ssr: false })


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface RootLayoutProps {
  params: {
    locale: string;
  };
  children: ReactNode;
}

export async function generateMetadata({ }) {
  const companyName = "talab | LogicProDev";
  const logoData = await GetLogoAndIcon();

  return {
    title: companyName,
    description: "منصتك المثالية لطلب قطع الصيانة لأصحاب المحلات",
    icons: {
      icon: logoData.data.data.icon,
    },
    openGraph: {
      images: logoData?.data?.data.logo,
      description: "منصتك المثالية لطلب قطع الصيانة لأصحاب المحلات",
      type: "website",
      title: "LogicProDev | Home Page",
    },
  };
}

export default async function RootLayout({ params: { locale }, children }: RootLayoutProps) {
  return (
    <html lang={locale} dir={dir(locale)} style={{ direction: locale == "ar" ? "rtl" : "ltr" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MyProvider>
          <div className="fixed lg:relative z-40 bg-white w-full">
            <Navbar locale={locale} logo="" />
          </div>

          <div>
            {children}
          </div>
        </MyProvider>
      </body>
    </html>
  );
}
